[package]
name = "MoonlightLevelGeneration"
version = "0.1.0"
authors = ["Kuju <kuju@veraegames.com>"]
edition = "2018"

[dependencies]
pixels = "0.2.0"
env_logger = "0.8.2"
winit = "0.24"
winit_input_helper = "0.9.0"
line_drawing = "0.8"
rand = "0.8.3"